server:
  port: 8087

spring:
  application:
    name: waiting-service
  datasource:
    url: ${WAITING_DB_URL:jdbc:mysql://waiting-db:3306/waiting?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${WAITING_DB_USERNAME:waiting}
    password: ${WAITING_DB_PASSWORD:waiting}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: waiting-service
    producer:
      client-id: waiting-service
  data:
    redis:
      host: ${WAITING_REDIS_HOST:waiting-redis}
      port: ${WAITING_REDIS_PORT:6379}
      database: ${WAITING_REDIS_DATABASE:0}

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
