server:
  port: 8086

spring:
  application:
    name: promotion-service
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
    consumer:
      group-id: promotion-service
    producer:
      client-id: promotion-service

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
