server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ticket-service
              uri: http://ticket-service:8081
              predicates:
                - Path=/api/tickets/**
            - id: payment-service
              uri: http://payment-service:8082
              predicates:
                - Path=/api/payments/**
            - id: member-service
              uri: http://member-service:8084
              predicates:
                - Path=/api/members/**
            - id: promotion-service
              uri: http://promotion-service:8086
              predicates:
                - Path=/api/promotions/**
            - id: waiting-service
              uri: http://waiting-service:8087
              predicates:
                - Path=/api/waiting/**
            - id: notification-service
              uri: http://notification-service:8088
              predicates:
                - Path=/api/notifications/**

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
