server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ticket-service
              uri: ${TICKET_SERVICE_URI:http://ticket-service:8081}
              predicates:
                - Path=/api/tickets/**
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI:http://payment-service:8082}
              predicates:
                - Path=/api/payments/**

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
