server:
  port: 8083

spring:
  application:
    name: queue-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: queue-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.apache.kafka: info

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
