services:
  k6:
    image: grafana/k6:latest
    profiles: [ "load" ]
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "sleep infinity" ]
    volumes:
      - ./load-testing:/scripts
    working_dir: /scripts
    networks:
      - core

networks:
  core:
    external: true
    name: ticket-system_core
