services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TICKET_SERVICE_URI: http://ticket-service:8081
      PAYMENT_SERVICE_URI: http://payment-service:8082
      TSID_NODE_ID: "3"
    depends_on:
      kafka:
        condition: service_healthy
      ticket-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - core
