name: ticket-system

services:
  kafka:
    image: apache/kafka:3.7.1
    restart: unless-stopped
    hostname: kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: 4L6g3nShT-eMCtKpAxAywA
    command:
      - /bin/bash
      - -c
      - |
        sed -i 's|^listeners=.*|listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093|' /opt/kafka/config/kraft/server.properties
        sed -i 's|^advertised.listeners=.*|advertised.listeners=PLAINTEXT://kafka:9092|' /opt/kafka/config/kraft/server.properties
        sed -i 's|^inter.broker.listener.name=.*|inter.broker.listener.name=PLAINTEXT|' /opt/kafka/config/kraft/server.properties
        echo 'listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT' >> /opt/kafka/config/kraft/server.properties
        echo 'controller.listener.names=CONTROLLER' >> /opt/kafka/config/kraft/server.properties
        /opt/kafka/bin/kafka-storage.sh format --ignore-formatted \
          --config /opt/kafka/config/kraft/server.properties \
          --cluster-id $$KAFKA_CLUSTER_ID
        exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 15s
      retries: 5
      timeout: 10s
      start_period: 30s
    networks:
      - core

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ticket-broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - core

volumes:
  kafka-data:

networks:
  core:
    driver: bridge
