services:
  notification-db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification
      MYSQL_USER: notification
      MYSQL_PASSWORD: notification
    ports:
      - "3312:3306"
    volumes:
      - notification-mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - core

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    environment:
      NOTIFICATION_DB_URL: jdbc:mysql://notification-db:3306/notification?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      NOTIFICATION_DB_USERNAME: notification
      NOTIFICATION_DB_PASSWORD: notification
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TSID_NODE_ID: "6"
    depends_on:
      kafka:
        condition: service_healthy
      notification-db:
        condition: service_healthy
    ports:
      - "8088:8088"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s
    networks:
      - core

volumes:
  notification-mysql-data:
